#%RAML 1.0 NamedExample
order:    
  id: 1
  placementDate: 2020-12-25T20:00:00
  customerName: "Silvio Santos"
  totalCost: 1800.00
  items:
   -
    id: 1
    name: "Microfone"
    cost: 200.00
    quantity: 4
   -
    id: 2
    name: "Camera"
    cost: 1000.00
    quantity: 1